# 0. 기본 설정

In [2]:
import csv
import pandas as pd
import numpy as np

from tqdm import tqdm
#from sklearn.cluster import KMeans
import matplotlib.pyplot  as plt
#from sklearn.preprocessing import MinMaxScaler
from tslearn.clustering import TimeSeriesKMeans
import warnings
warnings.filterwarnings(action='ignore')

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.cluster.k_means_ module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.cluster. Anything that cannot be imported from sklearn.cluster is now part of the private API.
  warnings.warn(message, FutureWarning)

# 1. 상권 - 추정매출 데이터 합치기

In [3]:
# 상권-추정매출 데이터 합치기

df13 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/서울시 우리마을가게 상권분석서비스(상권-추정매출)_2013.csv',encoding = 'CP949')
df14 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/서울시 우리마을가게 상권분석서비스(상권-추정매출)_2014.csv',encoding = 'CP949')
df15 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/서울시 우리마을가게 상권분석서비스(상권-추정매출)_2015.csv',encoding = 'CP949')
df16 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/서울시 우리마을가게 상권분석서비스(상권-추정매출)_2016.csv',encoding = 'CP949')
df17 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/서울시 우리마을가게 상권분석서비스(상권-추정매출)_2017.csv',encoding = 'CP949')
df18 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/서울시 우리마을가게 상권분석서비스(상권-추정매출)_2018.csv',encoding = 'CP949')
df19 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/서울시 우리마을가게 상권분석서비스(상권-추정매출)_2019.csv',encoding = 'CP949')
df20 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/서울시 우리마을가게 상권분석서비스(상권-추정매출)_2020.csv',encoding = 'CP949')

df13 = pd.DataFrame(df13) 
df14 = pd.DataFrame(df14) 
df15 = pd.DataFrame(df15) 
df16 = pd.DataFrame(df16) 
df17 = pd.DataFrame(df17) 
df18 = pd.DataFrame(df18) 
df19 = pd.DataFrame(df19) 
df20 = pd.DataFrame(df20)

In [4]:
resultSales_1 = pd.concat([df13, df14, df15, df16, df17, df18, df19, df20], axis=0, sort=False)
resultSales_1.to_csv("v7_서울시 우리마을가게 상권분석서비스(상권-추정매출).csv")

# 2. 데이터 불러오기

In [32]:
# csv 파일 읽어들이기 1 - 상권

v1 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/v1_서울시 우리마을가게 상권분석서비스(상권-직장인구).csv',encoding = 'CP949')
v2 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/v2_서울시 우리마을가게 상권분석서비스(상권-아파트).csv',encoding = 'CP949')
v3 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/v3_서울시 우리마을가게 상권분석서비스(상권-집객시설).csv',encoding = 'CP949')
v4 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/v4_서울시 우리마을가게 상권분석서비스(상권_상주인구).csv',encoding = 'CP949')
v5 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/v5_서울시 우리마을가게 상권분석서비스(상권-점포).csv',encoding = 'CP949')
v6 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/v6_서울시 우리마을가게 상권분석서비스(상권-추정유동인구).csv',encoding = 'CP949')
v7 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/v7_서울시 우리마을가게 상권분석서비스(상권-추정매출).csv',encoding = 'utf-8')
v8 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/v8_서울시 우리마을가게 상권분석서비스(상권-상권변화지표).csv',encoding = 'CP949')
v9 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/v9_서울시 우리마을가게 상권분석서비스(상권영역).csv',encoding = 'CP949')

In [33]:
# csv 파일 읽어들이기 2 - 상권배후지

v10 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/v10_서울시 우리마을가게 상권분석서비스(상권배후지-직장인구).csv',encoding = 'CP949')
v11 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/v11_서울시 우리마을가게 상권분석서비스(상권배후지-아파트).csv',encoding = 'CP949')
v12 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/v12_서울시 우리마을가게 상권분석서비스(상권배후지-집객시설).csv',encoding = 'CP949')
v13 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/v13_서울시 우리마을가게 상권분석서비스(상권배후지-상주인구).csv',encoding = 'CP949')
v14 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/v14_서울시 우리마을가게 상권분석서비스(상권배후지-점포).csv',encoding = 'CP949')
v15 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/v15_서울시 우리마을가게 상권분석서비스(상권배후지-추정유동인구).csv',encoding = 'CP949')
v16 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/v16_서울시 우리마을가게 상권분석서비스(상권배후지-추정매출).csv',encoding = 'utf-8')
v17 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/v17_서울시 우리마을가게 상권분석서비스(상권배후지-소득소비).csv',encoding = 'CP949')
v18 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/v18_서울시 우리마을가게 상권분석서비스(자치구별 상권변화지표).csv',encoding = 'CP949')
v19 = pd.read_csv('/Users/LG/Desktop/프로그래밍/한이음/Alldata/v19_서울시 우리마을가게 상권분석서비스(행정동별 상권변화지표).csv',encoding = 'CP949')

In [34]:
# 데이터프레임 형태로 바꿔주기

v1 = pd.DataFrame(v1) 
v2 = pd.DataFrame(v2) 
v3 = pd.DataFrame(v3) 
v4 = pd.DataFrame(v4) 
v5 = pd.DataFrame(v5) 
v6 = pd.DataFrame(v6) 
v7 = pd.DataFrame(v7) 
v8 = pd.DataFrame(v8) 
v9 = pd.DataFrame(v9) 
v10 = pd.DataFrame(v10) 
v11 = pd.DataFrame(v11) 
v12 = pd.DataFrame(v12) 
v13 = pd.DataFrame(v13) 
v14 = pd.DataFrame(v14) 
v15 = pd.DataFrame(v15) 
v16 = pd.DataFrame(v16) 
v17 = pd.DataFrame(v17) 
v18 = pd.DataFrame(v18) 
v19 = pd.DataFrame(v19)

# 3. 전체 데이터 확인

In [35]:
# 컬럼 이름 통일
v1.rename(columns = {"기준_년월_코드": "기준_년_코드"}, inplace=True)
v6.rename(columns = {"기준 년코드": "기준_년_코드"}, inplace=True)
v17.rename(columns = {"기준 년 코드": "기준_년_코드"}, inplace=True)

In [114]:
# concat로 모든 데이터 합치기
resultAll = pd.concat([v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13,v14,v15,v16,v17,v18,v19], axis=1, sort=False)
resultAll = resultAll.fillna(0)
resultAll

,기준_년_코드,기준_분기_코드,기준_분기_코드.1,상권_구분_코드_명,상권_코드,상권_코드_명,총_직장_인구_수,남성_직장_인구_수,여성_직장_인구_수,연령대_10_직장_인구_수,...,기준_년_코드,기준_분기_코드,행정동_코드,행정동_코드_명,상권_변화_지표,상권_변화_지표_명,운영_영업_개월_평균,폐업_영업_개월_평균,서울_운영_영업_개월_평균,서울_폐업_영업_개월_평균
0,2020.0,1.0,U,관광특구,1001496.0,강남 마이스 관광특구,15904.0,8904.0,7000.0,59.0,...,2020.0,1.0,11740700.0,둔촌2동,HL,상권축소,113.0,50.0,110.0,54.0
1,2020.0,1.0,U,관광특구,1001495.0,잠실 관광특구,24375.0,14199.0,10176.0,120.0,...,2020.0,1.0,11740690.0,둔촌1동,HH,정체,156.0,70.0,110.0,54.0
2,2020.0,1.0,U,관광특구,1001494.0,종로?청계 관광특구,32935.0,17150.0,15785.0,68.0,...,2020.0,1.0,11740685.0,길동,LL,다이나믹,104.0,48.0,110.0,54.0
3,2020.0,1.0,U,관광특구,1001493.0,동대문패션타운 관광특구,6054.0,2958.0,3096.0,36.0,...,2020.0,1.0,11740660.0,성내3동,HL,상권축소,111.0,47.0,110.0,54.0
4,2020.0,1.0,U,관광특구,1001492.0,명동 남대문 북창동 다동 무교동 관광특구,104830.0,53674.0,51156.0,423.0,...,2020.0,1.0,11740650.0,성내2동,LL,다이나믹,105.0,48.0,110.0,54.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1637384,0.0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0
1637385,0.0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0
1637386,0.0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0
1637387,0.0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0
1637388,0.0,0.0,0,0,0.0,0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0

### > 총 1,637,389 행 / 1,513 열

# 4. 데이터 전처리

### 4.1. 결측치 처리 - 0으로 대체

In [37]:
v2 = v2.fillna(0) # 아파트 세대수
v3 = v3.fillna(0) # 상권 집객시설 수
v12 = v12.fillna(0) # 상권배후지 집객시설 수

In [99]:
#v7.set_index("Unnamed: 0", inplace=True)

### * 추정매출 데이터 - '화장품' 업종만 추출하기

In [110]:
# 상권 - 추정매출
df7 = v7[(v7.서비스_업종_코드_명 == '화장품')]
df7 = pd.DataFrame(df7[['기준_년_코드','기준_분기_코드','상권_코드','당월_매출_금액']])

In [112]:
# 상권배후지 - 추정매출
df16 = v16[(v16.서비스_업종_코드_명 == '화장품')]
df16 = pd.DataFrame(df16[['기준_년_코드','기준_분기_코드','상권_코드','당월_매출_금액']])

### 4.2 이상치 처리 - IQR 방식

In [101]:
# IQR 기반 이상치 처리 함수
def outliers_iqr_upper(ys):
    quartile_1, quartile_3 = np.percentile(ys, [25, 75])
    iqr = quartile_3 - quartile_1
    lower_bound = quartile_1 - (iqr * 1.5)
    upper_bound = quartile_3 + (iqr * 1.5)
    return upper_bound
def outliers_iqr_lower(ys):
    quartile_1, quartile_3 = np.percentile(ys, [25, 75])
    iqr = quartile_3 - quartile_1
    lower_bound = quartile_1 - (iqr * 1.5)
    upper_bound = quartile_3 + (iqr * 1.5)
    return lower_bound

In [105]:
# 상권 [추정매출] - [당월_매출_금액] 데이터 이상치 처리
upper_df7 = outliers_iqr_upper(df7['당월_매출_금액'])
lower_df7 = outliers_iqr_lower(df7['당월_매출_금액'])

df7 = df7[df7.당월_매출_금액 < upper_df7]
df7 = df7[df7.당월_매출_금액 > lower_df7]

In [108]:
# 상권배후지 [추정매출] - [당월_매출_금액] 데이터 이상치 처리
upper_df16 = outliers_iqr_upper(df16['당월_매출_금액'])
lower_df16 = outliers_iqr_lower(df16['당월_매출_금액'])

df16 = df16[df16.당월_매출_금액 < upper_df16]
df16 = df16[df16.당월_매출_금액 > lower_df16]

# 5. 변수별 영향력 측정

### > 종속변수인 "매출액"에 대하여

# 6. 시계열 클러스터링

# 7. 의사결정트리

# 8. LSTM - 매출 예측